### delete_product.http
DELETE http://localhost:1337/api/products/product_5t0e1t4x5f
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzFhY2E3ZTNlYzYwOTNlMTY3MzBjMWYiLCJlbWFpbCI6ImpvaG40LmRvZUBleGFtcGxlLmNvbSIsIm5hbWUiOiJKb2huIERvZSIsImNyZWF0ZWRBdCI6IjIwMjQtMTAtMjRUMjI6MzA6MjIuODQ0WiIsInVwZGF0ZWRBdCI6IjIwMjQtMTAtMjRUMjI6MzA6MjIuODQ0WiIsIl9fdiI6MCwic2Vzc2lvbiI6IjY3MWQxZmNjN2YwMDZjMDMyNTI1YWVmYiIsImlhdCI6MTcyOTk2MTkzMiwiZXhwIjoxNzI5OTYyODMyfQ.Wd3ugfRAhxd_yVdrDSGaaDItpz-55U6CJD-vGqAYAsTn_k0mW0GiPGqTCt9CGGqQ7UlWSOHXoWzo-39KSRSj3jmJ8wu1OvxgWa4gMgFDosSnHgkMkTBp-A7DW9iO_6JUuWWsvwCihcMgEv36eOOQaUf_gGzg1uE6-IbsjHQ0W4QMJL8qzIvkU25cu7J3hvYQJ6kfGXI16pzzUdMZt5JSA6muvDkj99C43uVEmuxwxuo857AcwEWQWpybwlHI6up1uCN6R-OlBowl8lk6vaeQEGpXTYOAtyGoUoZM4FtDxRAOTrYrTbRq1XHhwIKcRFHdFnb2x84TleFg0Jy7YtMERw
