### Delete User Session
DELETE http://localhost:1337/api/sessions
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzFhY2E2YTNlYzYwOTNlMTY3MzBjMWIiLCJlbWFpbCI6ImpvaG4yLmRvZUBleGFtcGxlLmNvbSIsIm5hbWUiOiJKb2huIERvZSIsImNyZWF0ZWRBdCI6IjIwMjQtMTAtMjRUMjI6MzA6MDIuMTQzWiIsInVwZGF0ZWRBdCI6IjIwMjQtMTAtMjRUMjI6MzA6MDIuMTQzWiIsIl9fdiI6MCwic2Vzc2lvbiI6IjY3MWFkOGRjMDEyZGE4ZjY2YjY3MjU1NCIsImlhdCI6MTcyOTgxMjcwMCwiZXhwIjoxNzI5ODEzNjAwfQ.DzT1XYxMnSZ-0v5v6pcmLvAiPz_SKoPKoa5A9vBfqVewEfLJR4wxhBZJlQ6Ctd4he_lornwjXfPYyg2YMWS2bZ7W1m9kBCDCBGcUOTMsochoAhX6YHGmnPoVULmp-f0MydY_ixeT4MS92YdXvvD6ytkvAhtzrWncUM7fQ5QYdkykk0j7W_SUWU7P7RAFwLSkxbvLjnL8omGYLNKau3IuWfhlVQ5ksyXRb1x9Y2FqahHe6i6MUk8CAJTO766_gc-hLxCl4iiPPzsS-RusOAlgevyKa_8YMp6CfFoeW93VfFBgFp0FWuTap92UjMvgldRM-piWZNmrgoqSxahT_qz1Zg
Content-Type: application/json