### Get User Sessions
GET http://localhost:1337/api/sessions
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzFhY2E2YTNlYzYwOTNlMTY3MzBjMWIiLCJlbWFpbCI6ImpvaG4yLmRvZUBleGFtcGxlLmNvbSIsIm5hbWUiOiJKb2huIERvZSIsImNyZWF0ZWRBdCI6IjIwMjQtMTAtMjRUMjI6MzA6MDIuMTQzWiIsInVwZGF0ZWRBdCI6IjIwMjQtMTAtMjRUMjI6MzA6MDIuMTQzWiIsIl9fdiI6MCwic2Vzc2lvbiI6IjY3MWFkMmI1MTQ2M2ZmNTJmZDgzNmRjMSIsImlhdCI6MTcyOTgxMTEyNSwiZXhwIjoxNzI5ODEyMDI1fQ.H4ts1RiYOUZPpxLrhO7c6fKhRc-QY-4fyUIDyHjIKrmEjtAYvyo_BYSyM3viIH-Gs3g9sOBBWnZLrx1vk4Azixq2aQPajwSb3FHtbKfkhGp_fJrtcfanxz7nlczw-yMbMqKJu0AKDvUG1LzrvBvw96bja0s1B1BS0qnTE03f4phe36ire4WPjN7CfeseKeIjtzuQv9CjNcNUQytuZAlqF368LWbhPYKnyyYf-m4600FEGZSuFX2TjRmKc1gkxmKcB1y-G56kbILbH2zO4MXUJoPbSFXrvXZkXGPCeynIhc5OIrui_7cuhAG1cTSV3NAXMrldEORvrpx9BntLEI-NEQ
Content-Type: application/json