### Create User
POST http://localhost:1337/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "password": "password124",
  "passwordConfirmation": "password124",
  "email": "john3.doe@example.com"
}